version: '3.8'

services:
  web:
    build: . 
    command: gunicorn --bind 0.0.0.0:8000 blog_project.wsgi:application
    env_file:
      - .env  
    volumes:
      - ./staticfiles:/code/staticfiles
    expose:
      - 8000

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./staticfiles:/code/staticfiles
    depends_on:
      - web
